import { Component } from '@angular/core';
import { AuthHeaderComponent } from '../../components/auth-header/auth-header.component';
import { JobPreviewComponent } from '../../components/job-preview/job-preview.component';
import { ApiService } from '../../services/api.service';
import { CommonModule } from '@angular/common';
import { JobDescriptionComponent } from '../../components/job-description/job-description.component';
import { JobSearchComponent } from '../../components/job-search/job-search.component';
@Component({
  selector: 'app-jobs',
  standalone: true,
  imports: [
    AuthHeaderComponent,
    JobPreviewComponent,
    CommonModule,
    JobDescriptionComponent,
    JobSearchComponent,
  ],
  templateUrl: './jobs.component.html',
  styleUrl: './jobs.component.css',
})
export class JobsComponent {
  jobSearchResult: any[] = [];
  currentJob: any;

  constructor(private apiService: ApiService) {}

  setItem(newId: number) {
    this.currentJob = this.jobSearchResult.find((job) => job.id == newId);
  }

  ngOnInit() {
    // this.apiService
    //   .getJobs('Software Engineer', 'Toronto, ON', 0)
    //   .subscribe((res) => {
    //     this.jobSearchResult = res.data;
    //     this.currentJob = res.data[0];
    //   });

    this.jobSearchResult = {
      data: [
        {
          jobTypes: ['Full-time'],
          attributes: [
            'MVC',
            'Computer Science',
            'Data structures',
            'Full-time',
            'Java',
            "Master's degree",
            'C++',
            'C',
            "Bachelor's",
            'APIs',
            'Communication skills',
            'Python',
          ],
          id: 4,
          externalId: 'b193819787f5db34',
          title: 'Intern - Software Engineer',
          description:
            "<div>\n <div>\n  Job Description:\n </div>\n <div>\n   The Intern Experience:\n </div>\n <div>\n   At Rakuten, we pride ourselves on giving interns a genuine, immersive experience that has a direct impact on company objectives. You will do meaningful work, and with us, you’ll be a true member of the team. We are also invested in your growth as an individual and professional. That’s why you can expect curated events such as professional development workshops, interactions with Rakuten leadership, and relationship building opportunities with other interns and professionals at the company.\n </div>\n <div></div>\n <div>\n   You can visit \n  <div>\n   Rakuten.us\n  </div>, \n  <div>\n   our Muse profile\n  </div>, or listen to our feature on \n  <div>\n   The Internship Show Podcast\n  </div>, to learn more about Rakuten’s culture and values, and our internship program.\n </div>\n <div></div>\n <div>\n   Rakuten Rewards is a profitable, high growth e-commerce company based in San Mateo, CA. We are part of the Rakuten family of companies. Rakuten is a very progressive company providing Rakuten Rewards with substantial capital, access to great technology, and access to international markets. We're always interested in meeting talented individuals interested in helping us change the way the world shops, so if you're passionate about helping save people money and improving the shopping experience apply below!\n </div>\n <div></div>\n <div>\n   We are looking for an energetic, detail-oriented software developer to join a talented team of product marketers, software developers, and designers. As developer, you will support the delivery of a robust roadmap of new consumer facing product launches and feature enhancements. We are looking for a Co-op student who is creative and resourceful. You will be part of a fast-paced dynamic team.\n </div>\n <div></div>\n <div>\n   KEY RESPONSIBILITIES\n </div>\n <ul>\n  <li>\n   <div>\n     Develop multiple approaches to a solution, deploy them in an A/B test to our customers, learn and adapt from the results\n   </div></li>\n  <li>\n   <div>\n     Analyze, develop and recommend metrics to drive business decisions\n   </div></li>\n  <li>\n   <div>\n     Collaborate with project manager, developers, and business units to develop products &amp; services\n   </div></li>\n </ul>\n <div></div>\n <div>\n   QUALIFICATIONS\n </div>\n <ul>\n  <li>\n   <div>\n     Strong software development ability in either Java, C, C++, Python, algorithms and or similar\n   </div></li>\n  <li>\n   <div>\n     UI building with MVC principles a plus\n   </div></li>\n  <li>\n   <div>\n     Knowledge of API usage\n   </div></li>\n  <li>\n   <div>\n     Solid understanding of algorithms and data structures\n   </div></li>\n  <li>\n   <div>\n     Effective communication and collaborations skills\n   </div></li>\n </ul>\n <div></div>\n <div>\n   MINIMUM REQUIREMENTS\n </div>\n <ul>\n  <li>\n   <div>\n     Currently enrolled in a Bachelor, or Master’s program with an anticipated graduation date no earlier than December 2024\n   </div></li>\n  <li>\n   <div>\n     Relevant major or area of study in Computer Science, Computer Engineering, Software Engineering\n   </div></li>\n  <li>\n   <div>\n     Available for a 12-week full-time internship program in summer of 2024\n   </div></li>\n  <li>\n   <div>\n     Relevant prior internship experience (preferred)\n   </div></li>\n </ul>\n <div></div>\n <div>\n   Five Principles for Success\n  <br> Our worldwide practices describe specific behaviors that make Rakuten unique and united across the world. We expect Rakuten employees to model these 5 Shugi Principles of Success.\n  <br> \n  <br> Always improve, Always Advance - Only be satisfied with complete success - Kaizen\n  <br> Passionately Professional - Take an uncompromising approach to your work and be determined to be the best\n  <br> Hypothesize - Practice - Validate – Shikumika - Use the Rakuten Cycle to succeed in unknown territory\n  <br> Maximize Customer Satisfaction - The greatest satisfaction for our teams is seeing their customers smile\n  <br> Speed!! Speed!! Speed!! - Always be conscious of time - take charge, set clear goals, and engage your team\n </div>\n <div></div>\n <div>\n  <i> Rakuten provides equal employment opportunities to all employees and applicants for employment and prohibits discrimination and harassment of any type. Rakuten considers applicants for employment without regard to race, color, religion, age, sex, national origin, disability status, genetic information, protected veteran status, sexual orientation, gender, gender identity or expression, or any other characteristic protected by federal, state, provincial or local laws.</i>\n </div>\n</div>",
          location: 'Toronto, ON',
          address: null,
          employer: 'Rekuten Global',
          link: 'https://ca.indeed.com/applystart?jk=b193819787f5db34&from=vj&pos=top&mvj=0&spon=0&sjdu=o7sfz71MPdMgyiV0LZq0d4DDplm6SwWjHcxyoDIphKlzXIxC2XNIESer_K0BHQNXos_tx4krwhHQ3bzy4L35mr5hwuo5pIkCYZZLHWMg0keYtye8mQqD4GtqoEW34asqKBmrIXXYAJZYZeeUaseu8rLgPxO0U9yPafn87DpTCPBUJwzSfgR5oza9IWS7c7yDw9_XINGINv7OnqX9-Wv1cg&asub=mob&astse=274a54681a4d272e&assa=9057',
          createdAt: '2024-07-02T04:15:04.737Z',
          updatedAt: '2024-07-02T04:15:04.737Z',
        },
        {
          jobTypes: ['Full-time'],
          attributes: [
            'MVC',
            'Computer Science',
            'Data structures',
            'Full-time',
            'Java',
            "Master's degree",
            'C++',
            'C',
            "Bachelor's",
            'APIs',
            'Communication skills',
            'Python',
          ],
          id: 6,
          externalId: '9d071c72abd6c7d0',
          title: 'Intern - Software Engineer',
          description:
            "<div>\n <div>\n  Job Description:\n </div>\n <div>\n   The Intern Experience:\n </div>\n <div>\n   At Rakuten, we pride ourselves on giving interns a genuine, immersive experience that has a direct impact on company objectives. You will do meaningful work, and with us, you’ll be a true member of the team. We are also invested in your growth as an individual and professional. That’s why you can expect curated events such as professional development workshops, interactions with Rakuten leadership, and relationship building opportunities with other interns and professionals at the company.\n </div>\n <div></div>\n <div>\n   You can visit \n  <div>\n   Rakuten.us\n  </div>, \n  <div>\n   our Muse profile\n  </div>, or listen to our feature on \n  <div>\n   The Internship Show Podcast\n  </div>, to learn more about Rakuten’s culture and values, and our internship program.\n </div>\n <div></div>\n <div>\n   Rakuten Rewards is a profitable, high growth e-commerce company based in San Mateo, CA. We are part of the Rakuten family of companies. Rakuten is a very progressive company providing Rakuten Rewards with substantial capital, access to great technology, and access to international markets. We're always interested in meeting talented individuals interested in helping us change the way the world shops, so if you're passionate about helping save people money and improving the shopping experience apply below!\n </div>\n <div></div>\n <div>\n   We are looking for an energetic, detail-oriented software developer to join a talented team of product marketers, software developers, and designers. As developer, you will support the delivery of a robust roadmap of new consumer facing product launches and feature enhancements. We are looking for a Co-op student who is creative and resourceful. You will be part of a fast-paced dynamic team.\n </div>\n <div></div>\n <div>\n   KEY RESPONSIBILITIES\n </div>\n <ul>\n  <li>\n   <div>\n     Develop multiple approaches to a solution, deploy them in an A/B test to our customers, learn and adapt from the results\n   </div></li>\n  <li>\n   <div>\n     Analyze, develop and recommend metrics to drive business decisions\n   </div></li>\n  <li>\n   <div>\n     Collaborate with project manager, developers, and business units to develop products &amp; services\n   </div></li>\n </ul>\n <div></div>\n <div>\n   QUALIFICATIONS\n </div>\n <ul>\n  <li>\n   <div>\n     Strong software development ability in either Java, C, C++, Python, algorithms and or similar\n   </div></li>\n  <li>\n   <div>\n     UI building with MVC principles a plus\n   </div></li>\n  <li>\n   <div>\n     Knowledge of API usage\n   </div></li>\n  <li>\n   <div>\n     Solid understanding of algorithms and data structures\n   </div></li>\n  <li>\n   <div>\n     Effective communication and collaborations skills\n   </div></li>\n </ul>\n <div></div>\n <div>\n   MINIMUM REQUIREMENTS\n </div>\n <ul>\n  <li>\n   <div>\n     Currently enrolled in a Bachelor, or Master’s program with an anticipated graduation date no earlier than December 2024\n   </div></li>\n  <li>\n   <div>\n     Relevant major or area of study in Computer Science, Computer Engineering, Software Engineering\n   </div></li>\n  <li>\n   <div>\n     Available for a 12-week full-time internship program in summer of 2024\n   </div></li>\n  <li>\n   <div>\n     Relevant prior internship experience (preferred)\n   </div></li>\n </ul>\n <div></div>\n <div>\n   Five Principles for Success\n  <br> Our worldwide practices describe specific behaviors that make Rakuten unique and united across the world. We expect Rakuten employees to model these 5 Shugi Principles of Success.\n  <br> \n  <br> Always improve, Always Advance - Only be satisfied with complete success - Kaizen\n  <br> Passionately Professional - Take an uncompromising approach to your work and be determined to be the best\n  <br> Hypothesize - Practice - Validate – Shikumika - Use the Rakuten Cycle to succeed in unknown territory\n  <br> Maximize Customer Satisfaction - The greatest satisfaction for our teams is seeing their customers smile\n  <br> Speed!! Speed!! Speed!! - Always be conscious of time - take charge, set clear goals, and engage your team\n </div>\n <div></div>\n <div>\n  <i> Rakuten provides equal employment opportunities to all employees and applicants for employment and prohibits discrimination and harassment of any type. Rakuten considers applicants for employment without regard to race, color, religion, age, sex, national origin, disability status, genetic information, protected veteran status, sexual orientation, gender, gender identity or expression, or any other characteristic protected by federal, state, provincial or local laws.</i>\n </div>\n</div>",
          location: 'Toronto, ON',
          address: null,
          employer: 'Rakuten',
          link: 'https://ca.indeed.com/applystart?jk=9d071c72abd6c7d0&from=vj&pos=top&mvj=0&spon=0&sjdu=o7sfz71MPdMgyiV0LZq0d4DDplm6SwWjHcxyoDIphKnd_uRQOgOJMMMADnX30_KX_BwbadArtupLaXSByd_T_Rz5pkE_R2x3l0y3vMrUTB0z5oeuFS4l5wEOhflMXCDRB7_5HsUsNyeD_y3yq5rYZKGoxTZ8zq141NMDAlRPDDPzuRRsdva4EOhmmk7BMD5uw9_XINGINv7OnqX9-Wv1cg&asub=mob&astse=2e4722c3393810e2&assa=269',
          createdAt: '2024-07-02T04:15:04.737Z',
          updatedAt: '2024-07-02T04:15:04.737Z',
        },
        {
          benefits: [
            'Dental care',
            'Extended health care',
            'Life insurance',
            'RRSP match',
          ],
          jobTypes: ['Permanent', 'Full-time'],
          attributes: [
            'Extended health care',
            'RRSP match',
            'Permanent',
            'JD Edwards',
            'SAP',
            'Engineering',
            'Post-secondary education',
            'Full-time',
            'Process improvement',
            'NoSQL',
            'Metal fabrication',
            'Morning shift',
            'Dental care',
            'PHP',
            'Programmable logic controllers',
            'No university degree',
            'SolidWorks',
            'In-person',
            'Manufacturing',
            'Life insurance',
            'HTML5',
            'MySQL',
          ],
          id: 11,
          externalId: '56ee325466574ce7',
          title: 'Automation Engineer',
          description:
            '<p>GENERAL RESPONSIBILITY</p>\n<p>This role is for an Automation Engineer who will be responsible for all new automation projects and improvements to existing automation equipment thought DBG’s entire manufacturing facility. Troubleshoot equipment &amp; process issues on the line along with maintenance team. Implement any new equipment being installed on the line. Support entire plant with all new &amp; existing automation projects. PLC programming of weld fixture &amp; stamping dies. Designing of new automation systems from scratch. New electrical systems design. Integration of robots to PLCs (ABB, Motoman &amp; Kuka). Developing Preventative Maintenance plans for all new automation equipment.</p>\n<p><b>SPECIFIC RESPONSIBILITIES</b></p>\n<p>Maintain and encourage a safe work environment.</p>\n<p>Follow ISO / QS 900 &amp; TS16949 procedures.</p>\n<p>Automation lead for all new &amp; existing automation projects.</p>\n<p>Creation &amp; execution of project timelines and budgets.</p>\n<p>Ability to program &amp; troubleshoot PLCs.</p>\n<p>Ability to design &amp; read wiring diagrams.</p>\n<p>Mechanical design for new automation projects and improvements to existing equipment</p>\n<p>Develop preventative maintenance (PM) schedules for all new equipment.</p>\n<p>Programming experience in MySQL, NoSQL, PHP &amp; HTML is preferred but not necessary.</p>\n<p>Experience with JDE or SAP is preferred but not necessary.</p>\n<p>Work with Program Managers to ensure the successful launch and absorption of new programs.</p>\n<p>Arrange for and work with outside sub-suppliers as required to launch, maintain, or repair automated processes.</p>\n<p>Utilize best practices in assignment planning to make the most efficient use of resources, time and material.</p>\n<p>Experience with SolidWorks, NX, or equivalent 3D design software</p>\n<p><b>EDUCATION REQUIRED</b></p>\n<p>Post Secondary education in engineering. Degree or Certificate or equivalent experience.</p>\n<p><b>EXPERIENCE REQUIRED</b></p>\n<p>2 - 5 years in a manufacturing environment , working in a similar capacity.</p>\n<p>Knowledge and experience in PLC programming, robot programming, electrical systems design</p>\n<p>Knowledge and experience balancing assembly lines and process improvement.</p>\n<p>Job Types: Full-time, Permanent</p>\n<p>Benefits:</p>\n<ul>\n <li>Dental care</li>\n <li>Extended health care</li>\n <li>Life insurance</li>\n <li>RRSP match</li>\n</ul>\n<p>Schedule:</p>\n<ul>\n <li>Morning shift</li>\n</ul>\n<p>Experience:</p>\n<ul>\n <li>Automotive Industry: 2 years (required)</li>\n <li>Manufacturing: 2 years (required)</li>\n <li>PLC programming: 1 year (required)</li>\n <li>robot programming: 1 year (required)</li>\n <li>Metal fabrication: 1 year (required)</li>\n</ul>\n<p>Work Location: In person</p>',
          location: 'Mississauga, ON',
          address: null,
          employer: 'DBG Canada Limited',
          link: 'https://ca.indeed.com/viewjob?jk=56ee325466574ce7',
          createdAt: '2024-07-02T04:15:04.737Z',
          updatedAt: '2024-07-02T04:15:04.737Z',
        },
        {
          benefits: ['Dental care', 'Life insurance'],
          jobTypes: ['Full-time'],
          attributes: [
            'Overtime',
            'Overtime pay',
            'Full-time',
            'English',
            'Application development',
            'Dental care',
            "Bachelor's",
            'Monday to Friday',
            'Life insurance',
          ],
          id: 15,
          externalId: 'a76f9e67b0716358',
          title: 'Software Engineer',
          description:
            "<p>Software engineer</p>\n<p>Ielts 5 minimum</p>\n<p>Certificate in respective domain</p>\n<p>Ug degree minimum</p>\n<p>3 years experience in application development, testing, etc</p>\n<p>Job Type: Full-time</p>\n<p>Pay: From $3,500.00 per month</p>\n<p>Benefits:</p>\n<ul>\n <li>Dental care</li>\n <li>Life insurance</li>\n</ul>\n<p>Schedule:</p>\n<ul>\n <li>Monday to Friday</li>\n</ul>\n<p>Supplemental pay types:</p>\n<ul>\n <li>Overtime pay</li>\n</ul>\n<p>Education:</p>\n<ul>\n <li>Bachelor's Degree (required)</li>\n</ul>\n<p>Language:</p>\n<ul>\n <li>English (required)</li>\n</ul>",
          location: 'Toronto, ON',
          address: null,
          employer: 'Sutraflex Malaysia',
          link: 'https://ca.indeed.com/viewjob?jk=a76f9e67b0716358',
          createdAt: '2024-07-02T04:15:04.737Z',
          updatedAt: '2024-07-02T04:15:04.737Z',
        },
        {
          benefits: ['Dental care', 'Extended health care', 'Vision care'],
          jobTypes: ['Permanent'],
          attributes: [
            'Extended health care',
            'Permanent',
            'CSS',
            'Mobile applications',
            'iOS',
            'English',
            'Java',
            'SQL',
            'Dental care',
            'C++',
            'C',
            "Bachelor's",
            'JavaScript',
            'APIs',
            'Computer skills',
            'Vision care',
            'JSON',
            'Monday to Friday',
            'In-person',
            'College diploma',
            'Python',
            'MySQL',
          ],
          id: 28,
          externalId: 'faeb57068b43b3d6',
          title: 'Mobile Application Developer',
          description:
            "<p><b>About Hanson College</b><br>Hanson College, established in 2001, is a private educational institution that delivers college diploma programs and language training programs to international students. Our two campuses are located in Toronto and Brampton, Ontario. Our team is committed to providing an inclusive and accessible environment for higher education. We cultivate a diverse, supportive work environment because we have a passion for education, mentoring, and personal and professional growth. Joining Hanson to change life trajectories through education for generational impact in the global community.</p>\n<p>We are currently hiring a Mobile Applications Developer to join our team at our Toronto Campus!</p>\n<p><b>Job details</b></p>\n<ul>\n <li>Work location: 211 Consumers Road, Suite 2000, North York, ON M2J 4G8</li>\n <li>Permanent employment; Full time</li>\n <li>1 vacancy</li>\n <li>Start date: Starts as soon as possible</li>\n <li>Pay: $46.50 to $47.50 hourly (To be negotiated) / 37.5 hours per Week</li>\n <li>Benefits: Health benefits</li>\n</ul>\n<p><b>Overview</b></p>\n<p><b>Languages</b></p>\n<p>English</p>\n<p><b>Education</b></p>\n<p>Bachelor's degree</p>\n<p><b>Experience</b></p>\n<p>Experience an asset</p>\n<p><b>Responsibilities</b></p>\n<p>Tasks</p>\n<ul>\n <li>Write, modify, integrate and test software code</li>\n <li>Maintain existing computer programs by making modifications as required</li>\n <li>Communicate technical problems, processes and solutions</li>\n <li>Prepare reports, manuals and other documentation on the status, operation and maintenance of software</li>\n <li>Assist in the collection and documentation of user's requirements</li>\n <li>Assist in the development of logical and physical specifications</li>\n <li>Research and evaluate a variety of software products</li>\n <li>Write, modify, integrate and test software code for e-commerce and other Internet applications</li>\n <li>JavaScript Object Notation (JSON)</li>\n</ul>\n<p><b>Experience and specialization</b></p>\n<p>Computer and technology knowledge</p>\n<ul>\n <li>Android</li>\n <li>Xcode</li>\n <li>iOS</li>\n <li>C</li>\n <li>C++</li>\n <li>Java</li>\n <li>JavaScript</li>\n <li>CSS</li>\n <li>SQL</li>\n <li>Programming software</li>\n <li>API</li>\n <li>MySQL</li>\n <li>Python</li>\n <li>IntelliJ IDEA</li>\n</ul>\n<p><b>Additional information</b></p>\n<p>Work conditions and physical capabilities</p>\n<ul>\n <li>Fast-paced environment</li>\n <li>Work under pressure</li>\n <li>Attention to detail</li>\n</ul>\n<p>Personal suitability</p>\n<ul>\n <li>Accurate</li>\n <li>Efficient interpersonal skills</li>\n <li>Team player</li>\n <li>Integrity</li>\n <li>Accountability</li>\n</ul>\n<p><b>Benefits</b></p>\n<p>Health benefits</p>\n<ul>\n <li>Dental plan</li>\n <li>Health care plan</li>\n <li>Vision care benefits</li>\n</ul>\n<p><b>How to apply</b></p>\n<p>By email: hiring@canadahanson.com</p>\n<p><b>Inclusion and Equal Employment Opportunity:</b></p>\n<p>We are committed to fostering a diverse, inclusive, and accessible work environment. We value the unique skills and experiences each individual brings. If you require accommodation, don't hesitate to contact the Human Resources Department to make arrangements. We are pleased to consider all qualified applicants for employment without regard to race, colour, religion, sex, sexual orientation, gender identity, national origin, age, disability, or other legally protected factors.</p>\n<p>Job Type: Permanent</p>\n<p>Pay: $46.50-$47.50 per hour</p>\n<p>Expected hours: 37.5 per week</p>\n<p>Benefits:</p>\n<ul>\n <li>Extended health care</li>\n</ul>\n<p>Schedule:</p>\n<ul>\n <li>Monday to Friday</li>\n</ul>\n<p>Work Location: In person</p>",
          location: 'North York, ON',
          address: null,
          employer: 'Hanson Canada',
          link: 'https://ca.indeed.com/viewjob?jk=faeb57068b43b3d6',
          createdAt: '2024-07-02T04:29:12.246Z',
          updatedAt: '2024-07-02T04:29:12.246Z',
        },
        {
          benefits: [
            'Company events',
            'Dental care',
            'Extended health care',
            'Paid time off',
            'Vision care',
          ],
          jobTypes: ['Permanent', 'Full-time'],
          attributes: [
            'Extended health care',
            'Permanent',
            'Node.js',
            'Computer Science',
            'CSS',
            'React',
            'XML',
            'Full-stack development',
            'Writing skills',
            'Full-time',
            'NoSQL',
            'Git',
            'MongoDB',
            'E-commerce',
            '.NET',
            'Databases',
            'SQL',
            'Dental care',
            'AWS',
            'C++',
            "Bachelor's",
            'Paid time off',
            'JavaScript',
            'Version control systems',
            'Angular',
            'Hybrid work',
            'APIs',
            'Company events',
            'Vision care',
            'JSON',
            'Monday to Friday',
            'Communication skills',
            'Python',
            'HTML5',
          ],
          id: 48,
          externalId: '9139cbe54b46fcb9',
          title: 'Full Stack Developer',
          description:
            "<p><b>Opportunity:</b></p>\n<p>WeVend is currently seeking a Full Stack Developer to develop and maintain both front-end and back-end applications which support our break through payment processing technology. This position is based at our head office location in North York, ON. WeVend is a Fintech, iOT and payment device solutions provider, enabling seamless device control and payments technologies for targeted retail verticals.</p>\n<p><b>Duties</b></p>\n<ul>\n <li>Plan, develop, optimize, and maintain web applications using a variety of programming languages</li>\n <li>Collaborate with Solutions Architect, Third Party providers, and product managers to create new functions and features that are optimize for user experience</li>\n <li>Write clean, efficient, and well-documented code for various business verticals</li>\n <li>Conduct thorough testing and debugging of applications</li>\n <li>Stay up-to-date with industry trends and technologies to ensure the best practices are implemented</li>\n <li>Integrate data from various back-end services and databases</li>\n <li>Meet established commitments and plan personal work responsibly</li>\n <li>Gather and refine specifications and requirements based on technical needs</li>\n <li>Create and maintain software documentation for releases</li>\n <li>Troubleshoot application bugs and determine/implement resolutions</li>\n <li>Optimize and refactor existing code to improve performance and reliability</li>\n</ul>\n<p><b>What This Role Requires:</b></p>\n<ul>\n <li>Ability to explain technical issues to non-technical stakeholders</li>\n <li>High attention to details while helping others do the same</li>\n <li>Ownership of your work and your projects, establishing deadlines, and communicating progress proactively</li>\n <li>Eager to research and learn in a self-directed way (always improving)</li>\n <li>Critical thinking, problem-solving and resolution</li>\n <li>Being a strong team player who works well with a wide range of people from different parts of the business, customer base, and WeVend partnerships</li>\n</ul>\n<p><b>Qualifications</b></p>\n<ul>\n <li>Bachelor's degree in Computer Science, or related field</li>\n <li>Proven experience as a Full Stack Developer or similar role</li>\n <li>Strong development skills using Angular, HTML, CSS, JavaScript, NodeJS, NextJS, Python, C++, .NET, XML, React</li>\n <li>Experience with JSON, RestAPIs, AWS APIs</li>\n <li>Experience with developing payments, e-commerce, transaction processing platforms</li>\n <li>Experience with both SQL and NoSQL database systems such as MongoDB/Amazon DocumentDB</li>\n <li>Experience using version control systems such as Git</li>\n <li>Familiarity with cloud platforms such as AWS</li>\n <li>Experience with NoSQL database systems such as MongoDB/Amazon DocumentDB</li>\n <li>Strong communication and writing skills and ability create documentation/release notes</li>\n</ul>\n<p>If you are passionate about software development and enjoy working on diverse projects using cutting-edge technologies, we would love to have you join our team. We offer competitive salaries, opportunities for career growth, and a collaborative work environment that fosters innovation.</p>\n<p>Job Types: Full-time, Permanent</p>\n<p>Pay: $70,000.00-$80,000.00 per year</p>\n<p>Benefits:</p>\n<ul>\n <li>Company events</li>\n <li>Dental care</li>\n <li>Extended health care</li>\n <li>Paid time off</li>\n <li>Vision care</li>\n</ul>\n<p>Schedule:</p>\n<ul>\n <li>Monday to Friday</li>\n</ul>\n<p>Work Location: Hybrid remote in North York, ON M2N 6C6</p>",
          location: 'North York, ON',
          address: null,
          employer: 'WeVend',
          link: 'https://ca.indeed.com/viewjob?jk=9139cbe54b46fcb9',
          createdAt: '2024-07-02T04:46:54.049Z',
          updatedAt: '2024-07-02T04:46:54.049Z',
        },
        {
          jobTypes: ['Full-time'],
          attributes: [
            'CI/CD',
            'SAFe',
            'iOS development',
            'XML',
            'iOS',
            'Full-time',
            'Objective-C',
            'Git',
            'SOAP',
            "Bachelor's",
            'No university degree',
            'REST',
            'UX',
            'Hybrid work',
            'Agile',
            'Web services',
            'Design thinking',
            'JSON',
            'GraphQL',
            'Swift',
            'Pair programming',
            'Communication skills',
            'Debugging',
            'Experience design',
            'Design patterns',
          ],
          id: 55,
          externalId: 'c4f49d302448ad88',
          title: 'Senior iOS Developer',
          description:
            '<div>\n <p><b>WHO WE ARE:</b><br> Accenture Song accelerates growth and value for our clients through sustained customer relevance. Our capabilities span ideation to execution: growth, product and experience design; technology and experience platforms; creative, media and marketing strategy; and campaign, content and channel orchestration. With strong client relationships and deep industry expertise, we help our clients operate at the speed of life through the unlimited potential of imagination, technology and intelligence. Visit us at: www.accenture.com/song</p>\n <p></p>\n <p><br> Digital Products creates value for our clients, their employees, and their customers. We design and build impactful experiences fueled by Technology that change the way people work and live. With expertise in product strategy, design, innovation, and delivery transformation at scale, assisting with design thinking, integrating user-experience design/research, and impeccable development for native mobile, web, and embedded systems, we will help bring clarity to any omni-channel product vision.</p>\n <p></p>\n <p><br> There will never be a typical day at Accenture Song, but that’s why people love it here. The opportunities to make a difference while working on exciting client initiatives are limitless in this ever-changing space. Here’s a snapshot of your responsibilities:</p>\n <p></p>\n <p><b><br> THE WORK:</b></p>\n <p> Our Senior iOS Developers are experienced engineers eager to stay on the bleeding-edge of the mobile market across a broad spectrum of industries. You thrive on bringing mobile projects to life with clients, from concept to implementation. Your guidance and input drives technical design and development decisions. You enjoy providing mentorship to junior engineers and acting as a technical sounding board for peers and non-technical colleagues. This role invites seasoned engineers to exercise their deep expertise.</p>\n <br> \n <p></p>\n <ul>\n  <li> Work in a hands-on developer role on a cross-functional team including other developers, designers, product owners, scrum masters, testers, etc.</li>\n  <li> Work independently on development tasks and coach/guide team members within area of expertise</li>\n  <li> Ensure team members adhere to guidelines/procedures on highly complex or large-scale projects complying with the software development life cycle and delivery methodology (e.g. agile/scrum)</li>\n  <li> Conduct code reviews to ensure quality, standards compliance, re-usability and ease of maintenance</li>\n  <li> Provide technical support for escalated incidents/outages to ensure that they are resolved efficiently with minimal impact to stakeholders</li>\n  <li> Provide input into application release plans and roll-out strategy for new app releases and updates</li>\n  <li> Support a positive work environment that promotes service to the business, quality, innovation and teamwork and ensure timely communication of issues or points of interest</li>\n  <li> Rapidly innovate on concepts via self-initiated proofs of concept, and connect back to user and business value</li>\n </ul>\n</div>\n<p></p> \n<br> \n<div>\n <p><b>HERE’S WHAT YOU’LL NEED:</b></p>\n <ul>\n  <li> 5+ years experience developing iOS applications with Swift</li>\n  <li> 1+ years experience in building iOS apps using SwiftUI</li>\n  <li> 1+ years experience with Swift Concurrency and async/await</li>\n  <li> 1+ years experience with Apple’s Combine Framework</li>\n  <li> Experience working with Accessibility/Voiceover, Dynamic Type, and Dark Mode</li>\n  <li> Experience creating custom views from code using size classes or autolayout for dynamic screen size</li>\n  <li> Advanced skills in using Xcode and it’s included features, and xcodebuild toolchain</li>\n  <li> Experience with iOS application testing frameworks (XCTest/XCUITest), and debugging/profiling tools (Instruments)</li>\n  <li> Experience with design patterns like POP (Protocol Oriented Programming), MVVM and reactive architecture</li>\n  <li> Experience with App Store Connect, TestFlight, and the application publishing process</li>\n  <li> Experience with distributed source control systems (Git) in a medium/large team environment and understanding of branching strategies, pull requests, and hotfixes</li>\n  <li> Solid oral and written communication skills, ability to communicate technical concepts to non-technical audience</li>\n  <li> University degree or equivalent work experience </li>\n </ul>\n <p></p>\n <p><b>NICE TO HAVE:</b></p>\n <ul>\n  <li> Solid understanding of multithreaded applications</li>\n  <li> Understanding of IT Standards, UX Design, Accessibility and Agile Methodologies</li>\n  <li> Comfortable with collective code ownership and pair programming</li>\n  <li> Experience with SwiftUI and UIKit interoperability</li>\n  <li> Experience coding with Objective-C</li>\n  <li> Experience working with Frameworks</li>\n  <li> Experience working with Swift Package Manager</li>\n  <li> Experience working with Cocoapods</li>\n  <li> Experience with Web services such as GraphQL, REST, JAX-RS, XML-RPC, JSON-RPC, SOAP</li>\n  <li> Knowledge of CI/CD tools and scripts used for iOS development</li>\n  <li> Experience with custom view animation and transition</li>\n  <li> Experience working with Snapshot Testing</li>\n  <li> Experience working with a distributed team with both onshore and offshore developers</li>\n  <li> Certification in agile methodology in a technical role (SAFe, Scrum, etc.)</li>\n </ul>\n</div>',
          location: 'Toronto, ON',
          address: null,
          employer: 'Accenture',
          link: 'https://ca.indeed.com/applystart?jk=c4f49d302448ad88&from=vj&pos=top&mvj=0&spon=0&sjdu=o7sfz71MPdMgyiV0LZq0d4DDplm6SwWjHcxyoDIphKkXvqmm0u82sVQUwalGvVCbbXtRFJowsj2GiaBOuR3khgahQ6B_yYnjAmRuwUd25VKR08BWvEqhwKO0FBINvJqafb-K3T2mp4OLGF3n2rzLkbXgb4FuMA6v8hU6x7oRgKEb3mpV_UnhLGR2x8WflCiSw9_XINGINv7OnqX9-Wv1cg&asub=mob&astse=935c9fbea1d5ef73&assa=7586',
          createdAt: '2024-07-02T04:48:36.561Z',
          updatedAt: '2024-07-02T04:48:36.561Z',
        },
        {
          jobTypes: ['Permanent', 'Part-time', 'Full-time'],
          attributes: [
            'Permanent',
            'Part-time',
            'Full-time',
            'English',
            "Bachelor's",
          ],
          id: 102,
          externalId: '3b6274fd76debf43',
          title: 'Web developer',
          description:
            '<div>\n <ul>\n  <li>Education: Bachelor\'s degree</li> \n  <li>Experience: 1 year to less than 2 years</li> \n  <h2 class="jobSectionHeader"><b>Tasks</b></h2>\n  <li> Consult with clients to develop and document Website requirements</li>\n  <li> Write, modify, integrate and test software code</li>\n  <li> Maintain existing computer programs by making modifications as required</li>\n  <li> Prepare mock-ups and storyboards</li>\n  <li> Communicate technical problems, processes and solutions</li>\n  <li> Prepare reports, manuals and other documentation on the status, operation and maintenance of software</li>\n  <li> Source, select and organize information for inclusion and design the appearance, layout and flow of the Website</li>\n  <li> Assist in the collection and documentation of user\'s requirements</li>\n  <li> Create and optimize content for Website using a variety of graphics, database, animation and other software</li>\n  <li> Assist in the development of logical and physical specifications</li>\n  <li> Lead and co-ordinate multidisciplinary teams to develop Website graphics, content, capacity and interactivity</li>\n  <li> Research and evaluate a variety of software products</li>\n  <li> Conduct tests and perform security and quality controls</li>\n  <li> Write, modify, integrate and test software code for e-commerce and other Internet applications</li>\n  <li> Manage incidents</li> \n  <li>Work Term: Permanent</li> \n  <li>Work Language: English</li> \n  <li>Hours: 30 hours per week</li>\n </ul>\n</div>',
          location: 'North York, ON',
          address: null,
          employer: 'Socksmith Canada Inc',
          link: 'https://ca.indeed.com/applystart?jk=3b6274fd76debf43&from=vj&pos=top&mvj=0&spon=0&sjdu=o7sfz71MPdMgyiV0LZq0d4DDplm6SwWjHcxyoDIphKnSwknRK12JZDpby2h-s_EQ-yVAkNZuO_YX82M_0Oq_EX6xAA0cuPy6buy87RFCpGg8NgR9xZ1jisi8zqBcg-upJrio1naMCYQTPy8DgB_S5sC-AFCDCfjvbKhAO8LpuUJmyme00oYodzR_OuDfX8FCw9_XINGINv7OnqX9-Wv1cg&asub=mob&astse=d670d79df39a497b&assa=7676',
          createdAt: '2024-07-02T17:41:29.465Z',
          updatedAt: '2024-07-02T17:41:29.465Z',
        },
        {
          benefits: [
            'Casual dress',
            'Dental care',
            'Extended health care',
            'Life insurance',
            'Paid time off',
            'Work from home',
          ],
          jobTypes: ['Part-time', 'Full-time'],
          attributes: [
            'Casual dress',
            'Extended health care',
            'Computer Science',
            'Part-time',
            'Software Engineering',
            'Engineering',
            'Full-time',
            'English',
            'Java',
            'Application development',
            'Dental care',
            'Analysis skills',
            "Bachelor's",
            'Paid time off',
            'No university degree',
            'Work from home',
            'Hybrid work',
            'Monday to Friday',
            'Business requirements',
            'Leadership',
            'Communication skills',
            'Python',
            'Life insurance',
          ],
          id: 104,
          externalId: '605823d11f336ebf',
          title: 'Software Engineer',
          description:
            "<p><b>About Us: </b>Teix Financial is a prominent player in the Canadian no-medical life insurance market. We specialize in providing hassle-free, online life insurance solutions that cater to the diverse needs of our valued customers. With a commitment to innovation and excellence, we're dedicated to making the insurance experience simpler, more accessible, and secure.</p>\n<p><b>Job Description:</b></p>\n<p>We are seeking a highly motivated and experienced Software Engineer to join our dynamic team at Teix Financial. As a Software Engineer, you will play a pivotal role in the development and implementation of our life insurance administration platform. This role will encompass both hands-on coding responsibilities and leadership duties to ensure the platform's success and continuous enhancement. You will also oversee the integration and optimization of third-party software solutions such as CRM and contact center systems.</p>\n<p><b>Key Responsibilities:</b></p>\n<ul>\n <li><b>Software Development:</b> Lead the development efforts of our life insurance administration platform, ensuring its reliability, scalability, and performance.</li>\n <li><b>Team Collaboration:</b> Collaborate effectively with other developers, providing guidance, mentorship, and fostering a culture of innovation and excellence.</li>\n <li><b>Feature Development:</b> Drive the implementation of new features and enhancements to meet evolving business requirements and customer needs.</li>\n <li><b>Third-Party Software Integration:</b> Oversee the integration and utilization of third-party software solutions, including CRM and contact center systems, to enhance overall operations and customer experience.</li>\n <li><b>Technical Leadership:</b> Provide technical leadership, guidance, and best practices to the development team, promoting a culture of continuous improvement.</li>\n <li><b>Quality Assurance:</b> Ensure the platform's quality through rigorous testing and code reviews, adhering to industry standards and best practices.</li>\n <li><b>Performance Optimization:</b> Monitor and optimize the platform's performance, identifying and addressing bottlenecks and issues as they arise.</li>\n <li><b>Documentation:</b> Maintain clear and comprehensive documentation of code, processes, and system architecture.</li>\n</ul>\n<p><b>Qualifications:</b></p>\n<ul>\n <li>Bachelor's degree in Computer Science, Software Engineering, or a related field (or equivalent work experience).</li>\n <li>Proven experience as a software developer, with a track record of successful project delivery.</li>\n <li>Strong proficiency in programming languages such as Python, Java, or similar.</li>\n <li>Experience with web application development, including front-end and back-end technologies.</li>\n <li>Familiarity with CRM and contact center solutions.</li>\n <li>Leadership skills with the ability to lead and mentor a team of developers.</li>\n <li>Excellent problem-solving and analytical skills.</li>\n <li>Strong communication skills and the ability to collaborate effectively with cross-functional teams.</li>\n <li>A commitment to staying up-to-date with the latest industry trends and technologies.</li>\n</ul>\n<p><b>Why Teix Financial:</b></p>\n<ul>\n <li>Join a forward-thinking company at the forefront of online no-medical life insurance in Canada.</li>\n <li>Play a key role in shaping the future of our platform and the experiences of our customers.</li>\n <li>Competitive salary and benefits package.</li>\n <li>Opportunity for career growth and professional development.</li>\n <li>A collaborative and innovative work environment.</li>\n</ul>\n<p>If you're a passionate and skilled software engineer looking to make a significant impact in the insurance industry, we invite you to apply for the Software Engineer position at Teix Financial. Join us in revolutionizing the way Canadians access and manage their life insurance needs.</p>\n<p>Job Types: Full-time, Part-time</p>\n<p>Pay: $65,092.07-$102,000.00 per year</p>\n<p>Benefits:</p>\n<ul>\n <li>Casual dress</li>\n <li>Dental care</li>\n <li>Extended health care</li>\n <li>Paid time off</li>\n <li>Work from home</li>\n</ul>\n<p>Schedule:</p>\n<ul>\n <li>Monday to Friday</li>\n</ul>\n<p>Ability to commute/relocate:</p>\n<ul>\n <li>Aurora, ON L4G 6H8: reliably commute or plan to relocate before starting work (required)</li>\n</ul>\n<p>Education:</p>\n<ul>\n <li>Bachelor's Degree (preferred)</li>\n</ul>\n<p>Language:</p>\n<ul>\n <li>English (preferred)</li>\n</ul>\n<p>Work Location: Hybrid remote in Aurora, ON L4G 6H8</p>",
          location: 'Aurora, ON',
          address: null,
          employer: 'Teix Financial Inc',
          link: 'https://ca.indeed.com/viewjob?jk=605823d11f336ebf',
          createdAt: '2024-07-02T17:41:29.465Z',
          updatedAt: '2024-07-02T17:41:29.465Z',
        },
        {
          benefits: ['Work from home'],
          jobTypes: ['Temporary', 'Full-time', 'Fixed term contract'],
          attributes: [
            'Temporary',
            '8 hour shift',
            'Computer Science',
            'Ansible',
            'DevOps',
            'Full-time',
            'Java',
            'Application development',
            'AWS',
            "Bachelor's",
            'REST',
            'Work from home',
            'Scrum',
            'Hybrid work',
            'APIs',
            'Agile',
            'S3',
            'Fixed term contract',
            'DynamoDB',
            'Jenkins',
            'Python',
          ],
          id: 110,
          externalId: 'f935625eabc806a9',
          title: 'Amazon Connect Developer - 100% Remote',
          description:
            "<p><b>Amazon Connect Developer — Remote</b></p>\n<p>Our client in the insurance industry is seeking an experienced Amazon Connect Developer to join their Contact Centre Infrastructure (CCI) Operations Tier 2 development team. This team is responsible for migrating Tier 2 Contact Centres from legacy infrastructure to Amazon Connect. This role requires an in-depth knowledge of cloud contact center technologies, strong development skills, and a broad understanding of enterprise infrastructure to ensure the security, stability, and supportability of services.</p>\n<p><b>What is in it for you:</b></p>\n<ul>\n <li>Hourly salary of $89 to $104, based on experience.</li>\n <li>6-month contract with the potential for permanent employment.</li>\n <li>Full-time position: 37.50 hours per week.</li>\n <li>Enjoy the flexibility of remote work.</li>\n <li>Join a passionate and inclusive team of professionals.</li>\n</ul>\n<p><b>Responsibilities: </b></p>\n<ul>\n <li>Develop and manage contact flows and skill-based routing IVR applications using Amazon Connect.</li>\n <li>Design, build, and maintain AWS Lambda functions and DynamoDB tables.</li>\n <li>Collaborate with business stakeholders to capture, design, and build requirements.</li>\n <li>Ensure the security, stability, and supportability of the contact center infrastructure.</li>\n <li>Work closely with remote teams to deliver and support cloud-based contact center solutions.</li>\n</ul>\n<p><b>What you will need to succeed:</b></p>\n<ul>\n <li>Bachelor's degree in Computer Science or a related field, or proven industry experience.</li>\n <li>3-5 years of experience in a Contact Center environment.</li>\n <li>2 years of hands-on support and development experience with Amazon Web Services (AWS), specifically Connect, DynamoDB, S3, CloudFormation, and CloudWatch.</li>\n <li>Proven experience in developing contact flows and skill-based routing IVR applications.</li>\n <li>Strong backend development skills with experience in Python, Java, and REST API.</li>\n <li>Experience with DevOps tools such as Jenkins, Ansible, and Continuous Delivery/Deployment (CDD).</li>\n <li>Familiarity with the application development lifecycle, including Agile Scrum methodology.</li>\n <li>Experience working with remote teams.</li>\n</ul>\n<p><b>Why Recruit Action?</b></p>\n<p>Recruit Action (agency permit: AP-2000003) provides recruitment services through quality support and a personalized approach to job seekers and businesses. Only candidates who match hiring criteria will be contacted.</p>\n<p># SLFJP00005087</p>\n<p>Job Types: Full-time, Fixed term contract<br>Contract length: 6 months</p>\n<p>Pay: $89.00-$104.00 per hour</p>\n<p>Expected hours: 37.50 per week</p>\n<p>Benefits:</p>\n<ul>\n <li>Work from home</li>\n</ul>\n<p>Schedule:</p>\n<ul>\n <li>8 hour shift</li>\n</ul>\n<p>Education:</p>\n<ul>\n <li>Bachelor's Degree (required)</li>\n</ul>\n<p>Experience:</p>\n<ul>\n <li>Contact Center: 3 years (required)</li>\n <li>AWS Connect: 2 years (required)</li>\n <li>Legacy infrastructure: 2 years (preferred)</li>\n <li>Agile Scrum: 2 years (preferred)</li>\n <li>Back-end development (Python, Java, REST): 2 years (required)</li>\n</ul>\n<p>Work Location: Hybrid remote in Toronto, ON M2J 4Y1</p>",
          location: 'Toronto, ON',
          address: null,
          employer: 'Recrute Action Inc.',
          link: 'https://ca.indeed.com/viewjob?jk=f935625eabc806a9',
          createdAt: '2024-07-02T17:44:16.430Z',
          updatedAt: '2024-07-02T17:44:16.430Z',
        },
        {
          benefits: ['Extended health care', 'Paid time off'],
          jobTypes: ['Internship / Co-op'],
          attributes: [
            'Extended health care',
            'Computer Science',
            'React',
            'Engineering',
            'Spark',
            'Java',
            "Bachelor's",
            'Paid time off',
            'Scala',
            'Angular',
            'Internship / Co-op',
            'Communication skills',
            'Python',
            'Spring',
            'Hadoop',
          ],
          id: 121,
          externalId: '8211776de79c7fa6',
          title: 'Ratings – Software Engineer Intern',
          description:
            "<b>About the Role:</b>\n<br> <b>Grade Level (for internal use):</b> 05 \n<br>\n<br> <b>About the Role:</b>\n<br> <b>The Team:</b>\n<br> Our Ratings Technology Services and Technology Strategy Governance team enables a culture &amp; mindset of Customer-First with a focus on delivering value through disciplined program delivery. Continuing to improve our User experience and stability of systems, employee productivity, innovation &amp; overall employee engagement. \n<br>\n<br> <b>Responsibilities and Impact:</b>\n<br> Collaborating with teammates during technical designs and planning \n<br>Learn and adopt SAFE software development practices as part of our SDLC \n<br>Build, monitor, and maintain data ETL pipelines \n<br>Use Scala, Java, or Python to utilize Hadoop/Spark to collect and manage data at scale \n<br>Use Java and React/Angular to build web applications \n<br>Learn and leverage various cloud and data lake technologies and tools to enhance and maintain our overall infrastructure \n<br>Participate in team test coverage reviews and trainings \n<br>Demo completed work to stakeholders \n<br>\n<br> <b>What We’re Looking For:</b>\n<br> <b>Basic Required Qualifications:</b>\n<br> Working towards a Bachelors degree in a technical field of study in Engineering, Computer Science, Computer Engineering, Management Information Systems, or IT \n<br>Fully matriculated students with anticipated graduation date in Fall 2024 or Spring 2025 \n<br>Demonstrated passion or interest in one or more of our key industries \n<br>Excellent communication skills \n<br>Strong critical thinking and problem-solving skills \n<br>An aptitude to learn and adapt quickly in a rapidly changing environment \n<br>Intellectual curiosity and desire to learn new things, techniques, and technologies \n<br>\n<br> <b>Additional Preferred Qualifications:</b>\n<br> Experience using Python, Java, React and Databricks \n<br>\n<br> About S&amp;P Global Ratings \n<br>At S&amp;P Global Ratings, our analyst-driven credit ratings, research, and sustainable finance opinions provide critical insights that are essential to translating complexity into clarity so market participants can uncover opportunities and make decisions with conviction. By bringing transparency to the market through high-quality independent opinions on creditworthiness, we enable growth across a wide variety of organizations, including businesses, governments, and institutions. \n<br><b>S&amp;P Global Ratings is a division of S&amp;P Global (NYSE:</b> SPGI). S&amp;P Global is the world’s foremost provider of credit ratings, benchmarks, analytics and workflow solutions in the global capital, commodity and automotive markets. With every one of our offerings, we help many of the world’s leading organizations navigate the economic landscape so they can plan for tomorrow, today. \n<br>\n<br> For more information, visit www.spglobal.com/ratings \n<br>\n<br> What’s In It For You? \n<br>\n<br> <b>Our Purpose:</b>\n<br> Progress is not a self-starter. It requires a catalyst to be set in motion. Information, imagination, people, technology–the right combination can unlock possibility and change the world. \n<br>\n<br> Our world is in transition and getting more complex by the day. We push past expected observations and seek out new levels of understanding so that we can help companies, governments and individuals make an impact on tomorrow. At S&amp;P Global we transform data into Essential Intelligence®, pinpointing risks and opening possibilities. We Accelerate Progress. \n<br>\n<br> <b>Our People:</b>\n<br> We're more than 35,000 strong worldwide—so we're able to understand nuances while having a broad perspective. Our team is driven by curiosity and a shared belief that Essential Intelligence can help build a more prosperous future for us all. \n<br>\n<br> From finding new ways to measure sustainability to analyzing energy transition across the supply chain to building workflow solutions that make it easy to tap into insight and apply it. We are changing the way people see things and empowering them to make an impact on the world we live in. We’re committed to a more equitable future and to helping our customers find new, sustainable ways of doing business. We’re constantly seeking new solutions that have progress in mind. Join us and help create the critical insights that truly make a difference. \n<br>\n<br> <b>Our Values:</b>\n<br> Integrity, Discovery, Partnership \n<br>\n<br> At S&amp;P Global, we focus on Powering Global Markets. Throughout our history, the world's leading organizations have relied on us for the Essential Intelligence they need to make confident decisions about the road ahead. We start with a foundation of integrity in all we do, bring a spirit of discovery to our work, and collaborate in close partnership with each other and our customers to achieve shared goals. \n<br>\n<br> <b>Benefits:</b>\n<br> We take care of you, so you can take care of business. We care about our people. That’s why we provide everything you—and your career—need to thrive at S&amp;P Global. \n<br>\n<br> <b>Our benefits include:</b>\n<br> <b>Health &amp; Wellness:</b> Health care coverage designed for the mind and body. \n<br>\n<br> <b>Flexible Downtime:</b> Generous time off helps keep you energized for your time on. \n<br>\n<br> <b>Continuous Learning:</b> Access a wealth of resources to grow your career and learn valuable new skills. \n<br>\n<br> <b>Invest in Your Future:</b> Secure your financial future through competitive pay, retirement planning, a continuing education program with a company-matched student loan contribution, and financial wellness programs. \n<br>\n<br> <b>Family Friendly Perks:</b> It’s not just about you. S&amp;P Global has perks for your partners and little ones, too, with some best-in class benefits for families. \n<br>\n<br> <b>Beyond the Basics:</b> From retail discounts to referral incentive awards—small perks can make a big difference. \n<br><b>For more information on benefits by country visit:</b> https://spgbenefits.com/benefit-summaries \n<br>\n<br> <b>Diversity, Equity, and Inclusion at S&amp;P Global:</b>\n<br> At S&amp;P Global, we believe diversity fuels creative insights, equity unlocks opportunity, and inclusion drives growth and innovation – Powering Global Markets. Our commitment centers on our global workforce, ensuring that our people are empowered to bring their whole selves to work. It doesn’t stop there, we strive to better reflect and serve the communities in which we live and work, and advocate for greater opportunity for all. \n<br>\n<br> S&amp;P Global has a Securities Disclosure and Trading Policy (“the Policy”) that seeks to mitigate conflicts of interest by monitoring and placing restrictions on personal securities holding and trading. The Policy is designed to promote compliance with global regulations. In some Divisions, pursuant to the Policy’s requirements, candidates at S&amp;P Global may be asked to disclose securities holdings. Some roles may include a trading prohibition and remediation of positions when there is an effective or potential conflict of interest. Employment at S&amp;P Global is contingent upon compliance with the Policy. \n<br>\n<br> ----------------------------------------------------------- \n<br>\n<br> Equal Opportunity Employer \n<br>S&amp;P Global is an equal opportunity employer and all qualified candidates will receive consideration for employment without regard to race/ethnicity, color, religion, sex, sexual orientation, gender identity, national origin, age, disability, marital status, military veteran status, unemployment status, or any other status protected by law. Only electronic job submissions will be considered for employment. \n<br>\n<br> If you need an accommodation during the application process due to a disability, please send an email to: EEO.Compliance@spglobal.com and your request will be forwarded to the appropriate person. \n<br>\n<br> <b>US Candidates Only:</b> The EEO is the Law Poster http://www.dol.gov/ofccp/regs/compliance/posters/pdf/eeopost.pdf describes discrimination protections under federal law. \n<br>\n<br> ----------------------------------------------------------- 203 - Entry Professional (EEO Job Group) (inactive), 20 - Professional (EEO-2 Job Categories-United States of America), IFTECH203 - Entry Professional (EEO Job Group) \n<br>\n<br> <b>Job ID:</b> 295973 \n<br><b>Posted On:</b> 2024-05-16 \n<br><b>Location:</b> Toronto, Ontario, Canada",
          location: 'Toronto, ON',
          address: null,
          employer: 'S&P Global',
          link: 'https://ca.indeed.com/applystart?jk=8211776de79c7fa6&from=vj&pos=top&mvj=0&spon=0&sjdu=o7sfz71MPdMgyiV0LZq0d4DDplm6SwWjHcxyoDIphKkO0px39qIHsXCzWz7Dr5tH4SdSnBxrkQtNnGYLQ_GsEM231TAXbB2yB4mtct9UA7tHBQFyu7YBOAL_M6fgxuccjBsH3c-IrEQ9_RXJd_RlmsNPAfsaw6qrLjwLR4IXDs05JSxqqAAMYzhyWzYirJxnw9_XINGINv7OnqX9-Wv1cg&asub=mob&astse=2fdb4168cb23d5bd&assa=2400',
          createdAt: '2024-07-02T18:56:14.182Z',
          updatedAt: '2024-07-02T18:56:14.182Z',
        },
        {
          jobTypes: ['Full-time'],
          attributes: [
            'Go',
            'Node.js',
            'Computer Science',
            'React',
            'Engineering',
            'Full-time',
            'AWS',
            "Bachelor's",
            'PostgreSQL',
            'Redis',
            'DynamoDB',
            'AI',
            'TypeScript',
            'Python',
            'React Native',
          ],
          id: 122,
          externalId: '6ecb9b4ad45a747e',
          title: 'Software Engineer I (Toronto)',
          description:
            "<div>\n <p><b>We'd love to hear from you if you like:</b></p>\n <ul>\n  <li><p> Making a big impact on Day One with a Forbes Top Startup Employer</p></li>\n  <li><p> Working at a startup that has traction ($240M in funding, 40X revenue growth in 4 years)</p></li>\n </ul>\n <ul>\n  <li><p> Working with a newer tech stack and building products that have a real impact (Jerry saves the average person $1K a year)</p></li>\n  <li><p> Mentorship from talented engineering leaders and peers<b> </b>who have built and scaled companies like Nvidia, Kuaishou, Cepton, and Tiktok</p></li>\n  <li><p> Meritocracy: we promote based on performance, not tenure</p></li>\n </ul>\n <p></p>\n <p><b> About the opportunity:</b></p>\n <p> Jerry is building the first AI-powered AllCar app to redefine car ownership. The average American spends over 20% of their annual income on their vehicle, yet every part of owning and managing a car is painful – lack of transparency, poor service, high costs, etc. We are simplifying and automating every step of car ownership, all streamlined on our mobile app. We started with insurance shopping in 2019, since then we’ve launched loan refinancing, real-time driving insights, car diagnostics, a repair marketplace, and a GPT-4 chatbot. Our engineering team isn’t just focused on making something that works, we want to make something that works <i>exceptionally well</i>. If you want to contribute to something that matters and is actively making car ownership easier, simpler, and more accessible for 5M+ people, join us!</p>\n <p></p>\n <p> We are looking for new graduates in the Toronto area to join our engineering team! We are in growth mode and have aggressive goals to scale our technology and our business in the next few years as we go from 5M to 50M users. We don't require any specific work experience but we <i>are</i> looking for the following characteristics: passion for learning, hustle, and ownership. The pace of learning at a startup like Jerry is unbeatable. You can expect your scope of responsibilities to grow quickly if you excel in your role and demonstrate a willingness to keep learning and growing. If you’re looking for an opportunity to accelerate your career, we are hiring across multiple engineering teams!</p>\n <p></p>\n <p><b> Our tech stack:</b></p>\n <ul>\n  <li><p> Hosting infra: AWS</p></li>\n  <li><p> React for web frontend</p></li>\n  <li><p> NodeJS + Typescript for backend development</p></li>\n  <li><p> React (mobile app is written in React Native)</p></li>\n  <li><p> Redis, Postgres, DynamoDB for backend storage</p></li>\n  <li><p> Python for data pipeline and ML</p></li>\n  <li><p> Clickhouse for data warehouse</p></li>\n  <li><p> Python + Go for infrastructure as code and continuous integration</p></li>\n </ul>\n <p></p>\n <p><b> What we are looking for:</b></p>\n <ul>\n  <li><p> Bachelor's degree in computer science or engineering</p></li>\n  <li><p> Any internship, co-op, or summer work experience is an asset</p></li>\n </ul>\n <p></p>\n <p><i> Jerry is proud to be an Equal Employment Opportunity employer. We prohibit discrimination based on race, religion, color, national origin, sex, pregnancy, reproductive health decisions or related medical conditions, sexual orientation, gender identity, gender expression, age, veteran status, disability, genetic information, or other characteristics protected by applicable local, state or federal laws. </i></p>\n <p></p>\n <p><i>Jerry is committed to providing reasonable accommodations for individuals with disabilities in our job application process. If you need assistance or an accommodation due to a disability, please contact us at </i><i>recruiting@getjerry.com</i></p>\n <p></p>\n <p><b> About Jerry:</b></p>\n <p> Jerry is America’s first and only AllCar app. We are redefining and radically improving how people manage owning a car, one of their most expensive and time-consuming assets.</p>\n <p></p>\n <p> Backed by artificial intelligence and machine learning, Jerry simplifies and automates owning and maintaining a car while providing personalized services for all car owners' needs. We spend every day innovating and improving our AI-powered app to provide the best possible experience for our customers. From car insurance and financing to maintenance and safety, Jerry does it all.</p>\n <p></p>\n <p> We are the #1 rated and most downloaded app in our category with a 4.7 star rating in the App Store. We have more than 6 million customers — and we’re just getting started.</p>\n <p></p>\n <p> Jerry was founded in 2017 by serial entrepreneurs and has raised more than $242 million in financing.</p>\n <p></p>\n <p> Join our team and work with passionate, curious and egoless people who love solving real-world problems. Help us build a revolutionary product that’s disrupting a massive market.</p>\n</div>",
          location: 'Toronto, ON',
          address: null,
          employer: 'Jerry',
          link: 'https://ca.indeed.com/applystart?jk=6ecb9b4ad45a747e&from=vj&pos=top&mvj=0&spon=0&sjdu=o7sfz71MPdMgyiV0LZq0d4DDplm6SwWjHcxyoDIphKm4xzneNK5j8Fum1QYYKydIqOqFXPNULmI5OQMHbF43tuOpdDdX_Lw9adQL5I2cJmMC6iM0UuGrnt7JKsWBYQMyQ_bXd36V1XFC0Q_UiB6XUUnAqlVBdsfaxrbox-ezTxo3Ql2N0Cr8PHHeen-xLVFdw9_XINGINv7OnqX9-Wv1cg&asub=mob&astse=62137f69643ecc62&assa=2950',
          createdAt: '2024-07-02T18:56:14.182Z',
          updatedAt: '2024-07-02T18:56:14.182Z',
        },
        {
          externalId: '180fc9397688b02a',
          title: 'Senior Software Engineer - Automotive',
          description:
            '<div>\n <div>\n  Are you ready to be part of a leading global engineering design house specializing in the design and development of embedded software/hardware, electronics, and electro-mechanics?\n </div>\n <div></div>\n <div>\n  <b><br> What we’re looking for</b>\n </div>\n <div></div>\n <ul>\n  <li><br> Highly motivated and dynamic professionals</li>\n  <li>Motivated designers with broad backgrounds and service mindset to be a consultant</li>\n  <li> Professionals with ability to work both with in-house projects and on-site assignments at our customer’s locations</li>\n </ul> \n <h3 class="jobSectionHeader"><b>What you\'ll do</b></h3>\n <ul>\n  <li> Develop Android applications with a focus on efficiency, reliability, and performance.</li>\n  <li> Collaborate with cross-functional teams to define, design, and ship new features.</li>\n  <li> Ensure the quality and responsiveness of applications by conducting thorough testing and troubleshooting.</li>\n </ul>\n <h3 class="jobSectionHeader"><b> What you\'ll need to get the job done</b></h3>\n <ul>\n  <li> Proficient in developing Android apps with a proven track record.</li>\n  <li> Strong programming skills in C++, Kotlin, or Java.</li>\n  <li> Experience with version control using Git (GitHub) and continuous integration tools like Jenkins.</li>\n  <li> Excellent communication skills to effectively collaborate with team members and stakeholders.</li>\n  <li> In-depth understanding of Android AOSP (Android Open Source Project).</li>\n  <li> Prior experience developing HMI (Human-Machine Interface) software for infotainment or mobile platforms.</li>\n  <li> Familiarity with Agile development processes for efficient project management.</li>\n  <li> Experience in building and contributing to the AOSP project.</li>\n  <li> Knowledge of software development on embedded QNX OS or Android-based platforms.</li>\n  <li> Proficiency in unit testing and mock frameworks to ensure code quality.</li>\n  <li> Experience with AutoSAR communication framework.</li>\n  <li> Ability to develop distributed software based on SOA (Service-Oriented Architecture) designs for communication efficiency.</li>\n </ul>\n <div>\n   #SyntronicP1\n </div>\n <div></div>\n <div>\n  <b><br> What you’ll love about us</b>\n </div>\n <div></div>\n <ul>\n  <li><br> <b>Company Culture</b> – outstanding people and a flexible work environment with lots of after work activities/groups! It’s so great, we even won an award for it!</li>\n  <li> <b>Work/Life Balance</b> – 4 weeks holidays to start and work that stays at work!</li>\n  <li> <b>Career Growth Opportunities</b> – being a design house keeps variety in your work. New opportunities happening all the time!</li>\n  <li><b> Great Benefits</b> – and, they start the same day you do… and, they include your family… and, the company matches your RRSP contributions!</li>\n </ul>\n <div></div>\n <div>\n  <b><br> About Syntronic Canada</b>\n </div>\n <div>\n   Syntronic provides our customers a complete portfolio of professional services to support their product development including research &amp; development, new product introduction, manufacturing, and aftermarket services. We adopt the latest technologies in electronics design and software development with a pool of technically skilled staff around the world. Among our customers and partners are some of the world’s most technically intensive businesses and organizations. This pushes us forward in designing to satisfy our customers’ needs with a focus on quality, competence, capacity and continuity.\n  <br> \n </div>\n <div></div>\n <br> \n <div>\n  Syntronic values diversity in the workplace. All qualified applicants will receive consideration for employment without regard to race, colour, religion, sex, sexual orientation, gender identity, national origin, disability or protected veteran status. If you require accommodation due to a disability at any time during the recruitment and/or assessment process, please contact our recruiting team and we will make all reasonable efforts to accommodate your request.\n </div>\n</div>',
          location: 'Markham, ON',
          addresss: null,
          employer: 'Syntronic',
          jobTypes: [],
          link: 'https://ca.indeed.com/applystart?jk=180fc9397688b02a&from=vj&pos=top&mvj=0&spon=0&sjdu=o7sfz71MPdMgyiV0LZq0d4DDplm6SwWjHcxyoDIphKkQOtrnmV1eIBTg58UUhonXbAvHTcAktGhZIxv3JGAqjf3FKez9mVzj4zOlusnO_NKWUE7GSsPBX9cEN6ibaclSzSrYv2TsytOFjjPUKtrVry36xl9mad4gtBrkPd3_tXfcIGD_WRHjuksrMVHa63bvw9_XINGINv7OnqX9-Wv1cg&asub=mob&astse=cdec09c403a37678&assa=2532',
          attributes: [
            'Kotlin',
            'Git',
            'Java',
            'C++',
            'Project management',
            'Continuous integration',
            'Software development',
            'GitHub',
            'Agile',
            'Unit testing',
            'Service-oriented architecture',
            'Jenkins',
            'Communication skills',
          ],
        },
        {
          externalId: '80a3e6802caed554',
          title: 'MTS 2, Software Engineer',
          description:
            "<div>\n <p>At eBay, we're more than a global ecommerce leader — we’re changing the way the world shops and sells. Our platform empowers millions of buyers and sellers in more than 190 markets around the world. We’re committed to pushing boundaries and leaving our mark as we reinvent the future of ecommerce for enthusiasts.</p>\n <p></p>\n <p> Our customers are our compass, authenticity thrives, bold ideas are welcome, and everyone can bring their unique selves to work — every day. We're in this together, sustaining the future of our customers, our company, and our planet.</p>\n <p></p>\n <p> Join a team of passionate thinkers, innovators, and dreamers — and help us connect people and build communities to create economic opportunity for all.</p>\n <p></p>\n <p> Are you looking for a company that inspires passion, courage and imagination, where you can be part of the team shaping the future of global commerce? Want to shape how millions of people buy, sell, connect, and share around the world? If you’re interested in joining a purpose driven community that is dedicated to creating an ambitious and inclusive workplace, join eBay – a company you can be proud to be a part of.</p>\n <p></p>\n <p> eBay's Buyer Experience engineering team is looking for an outstanding Staff Engineer to work with as we redefine the face of eBay. You’ll be working with a world class team of engineers, designers, product managers, and analysts to create great products that make a difference on one of the world’s most trafficked and loved websites.</p>\n <p></p>\n <p> The ideal candidate has a deep understanding of building large scale applications, low latency API’s, data pipelines, and a high focus on capability oriented architecture. As the lead engineer you will oversee aspects of the software lifecycle : design, development, testing and experimentation.</p>\n <p></p>\n <p><b> Primary Job Responsibilities</b></p>\n <p></p>\n <p><b> On a day-to-day basis, you’d:</b></p>\n <ul>\n  <li><p> Be a hands on technical lead, work closely with a skilled team of engineers</p></li>\n  <li><p> Hire top talent, coach and mentor</p></li>\n  <li><p> Use best practices to write clean, maintainable code for the project, and create a high performant delightful experience for customers</p></li>\n  <li><p> Identify and address performance bottlenecks</p></li>\n  <li><p> Be responsible for major projects and features from design phase to coding and testing</p></li>\n  <li><p> Work closely with product managers, engineering leaders, scientists and collaborate with partner teams to execute a challenging roadmap</p></li>\n </ul>\n <p></p>\n <p><b> Job Requirements</b></p>\n <ul>\n  <li><p> Exceptional programming skills in Java / Scala</p></li>\n  <li><p> Experience building and consuming horizontally scalable RESTful API’s, GraphQL and distributed systems</p></li>\n  <li><p> Experience with big data technologies like Spark, Flink, and Kafka</p></li>\n  <li><p> Hands on experience with Javascript / Web Frameworks is a plus</p></li>\n  <li><p> Self-driven and ability to get things done</p></li>\n  <li><p> Experience with scrum or other agile software development methodology</p></li>\n  <li><p> A constant desire to improve and learn</p></li>\n  <li><p> Bachelor’s degree and 10+ years (or) a MS in Computer Science and 7+ years of software design and relevant experience</p></li>\n </ul>\n <p></p>\n <p> Please see the Talent Privacy Notice for information regarding how eBay handles your personal data collected when you use the eBay Careers website or apply for a job with eBay.</p>\n <p></p>\n <p> eBay is an equal opportunity employer. All qualified applicants will receive consideration for employment without regard to race, color, religion, national origin, sex, sexual orientation, gender identity, veteran status, and disability, or other legally protected status. If you have a need that requires accommodation, please contact us at talent@ebay.com. We will make every effort to respond to your request for accommodation as soon as possible. View our accessibility statement to learn more about eBay's commitment to ensuring digital accessibility for people with disabilities.</p>\n <p></p>\n <p> Jobs posted with location as \"Remote - United States (Excludes: HI, NM)\" excludes residents of Hawaii and New Mexico.</p>\n <p></p>\n <p><br> This website uses cookies to enhance your experience. By continuing to browse the site, you agree to our use of cookies. Visit our Privacy Center for more information.</p>\n</div>",
          location: 'Toronto, ON',
          addresss: null,
          employer: 'eBay',
          jobTypes: [],
          link: 'https://ca.indeed.com/applystart?jk=80a3e6802caed554&from=vj&pos=top&mvj=0&spon=0&sjdu=o7sfz71MPdMgyiV0LZq0d4DDplm6SwWjHcxyoDIphKnTlFV5DFTXFiAixDhZy8wPJ3gcA60RP21q7hfvGSg7eLKpoV8K683ersp8aZdgnKf8hp_xkW9-f24D56Dc73qUHicSd0Xo8Y2fBMCUbIlQHvp8MRdZgtsn9i2tx-AqebNvzeev8Nv2xHYQrE6NWFQ8w9_XINGINv7OnqX9-Wv1cg&asub=mob&astse=7212c16a5c44f79d&assa=3121',
          attributes: [
            'Computer Science',
            'Big data',
            'Spark',
            'Remote',
            'Java',
            "Master's degree",
            "Bachelor's",
            'JavaScript',
            'Distributed systems',
            'Scala',
            'REST',
            'Scrum',
            'Software development',
            'APIs',
            'Agile',
            'Kafka',
            'GraphQL',
          ],
        },
        {
          externalId: '642c35f9360340aa',
          title: 'Lead Software Engineer (Node.js and PHP)',
          description:
            "<b>Title:</b> Lead Software Engineer (Node.js and PHP) \n<br>\n<br> <b>Location:</b> Toronto, ON, Canada (Hybrid) \n<br>\n<br> <b>Type:</b> Full-Time, Permanent \n<br>\n<br> <b>Introduction:</b>\n<br> Join a rock-solid organization as our client’s next Lead Software Engineer and sit at the center of projects that drives decisions. You’ll help one of Canada's most trusted organizations work on the latest project, and be rewarded with great opportunities. \n<br>\n<br> <b>Job Description:</b>\n<br> \n<ul> \n <li>Producing high-quality, efficient code with our client's technology stack: Node.js, PHP and Python.</li> \n <li>Designing scalable web architectures (leveraging AWS) that align with business goals and support product vision</li> \n <li>Working with Front end technologies like JavaScript, TypeScript, Angular, React, Vue.js, NestJS or Nuxt is a big plus.</li> \n <li>Collaborating with product teams to translate requirements into technical solutions, using your expertise in our core technologies.</li> \n <li>Optimizing development processes, including containerization (Docker), CI/CD, and system reliability.</li> \n <li>Providing architectural guidance and mentoring teams on best practices within our client's tech stack.</li> \n <li>Fueling the growth of our organization and industry-leading technologies and systems</li> \n <li>Mentor and be mentored, upholding the highest standards for rigorously tested, well-architected code, and operational efficiency within our chosen tech stack.</li> \n</ul> <b>Must Haves:</b>\n<br> \n<ul> \n <li>At least 10+ years of combined development experience, with a focus on modern web technologies and solution architecture principles.</li> \n <li>Track record of collaborating with product teams to shape well-architected solutions.</li> \n <li>Producing high-quality, efficient code with our client's technology stack: Node.js, PHP and Python.</li> \n <li>Proven experience with AWS, CI/CD implementation, infrastructure design, and ensuring system reliability.</li> \n <li>Working with Front end technologies like JavaScript, TypeScript, Angular, React, Vue.js, NestJS or Nuxt is a big plus.</li> \n <li>Deep understanding of architectural patterns (SOLID, microservices, etc.), data structures, algorithms, and system design tailored to web applications.</li> \n <li>Strong grasp of containerization (Docker), CI/CD pipelines, Infrastructure as Code (IaC), and AWS services.</li> \n <li>Database design (SQL/NoSQL), with experience building distributed systems for web use cases.</li> \n <li>Proficiency in testing (unit, integration, functional), monitoring, and alerting.</li> \n <li>Ability to lead and mentor, fostering a culture of engineering excellence and architectural integrity.</li> \n <li>Excellent communication skills – you can clearly articulate complex technical concepts in a collaborative environment.</li> \n <li>Familiarity with Site Reliability Engineering (SRE) concepts and their application to web solutions</li> \n <li>Web server infrastructure experience.</li> \n <li>Understanding of emerging technologies (AI/ML, blockchain, etc.) applicable to web development.</li> \n <li>Action Oriented: Enthusiasm for designing, building, and iterating on solutions. They proactively tackle challenges and opportunities.</li> \n <li>Dealing with Ambiguity: Ability to design and execute solutions in a dynamic tech environment where priorities and technologies might shift.</li> \n <li>Innovation Management: Not just coding, but also evaluating new ideas and creatively applying them to solve problems.</li> \n <li>Problem Solving: Strong analytical skills for debugging, root-cause analysis, and developing optimal solutions.</li> \n <li>Collaboration: Works effectively with product teams and engineers to deliver well-architected solutions.</li> \n <li>Communication: Clearly articulates technical concepts to both technical and non-technical audiences.</li> \n <li>Learning on the Fly: Stays up-to-date with the latest advancements in web development technologies.</li> \n</ul> We are an equal opportunity employer. \n<br>\n<br> We evaluate qualified applicants without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, disability, veteran status, and other protected characteristics. \n<br>\n<br> Apply now—we look forward to meeting you!!! \n<br>\n<br> INDHuntelGlobalToronto \n<br>\n<br> #LI-DNI",
          location: 'Toronto, ON',
          addresss: null,
          employer: 'Drake International Inc',
          jobTypes: ['Permanent', 'Full-time'],
          link: 'https://ca.indeed.com/applystart?jk=642c35f9360340aa&from=vj&pos=top&mvj=0&spon=0&sjdu=o7sfz71MPdMgyiV0LZq0d4DDplm6SwWjHcxyoDIphKlXqbCK_fn2oaLVWhG1aj7C--QNSqDVpYd67KY8HteZqwcbRjl1kqw6emo1K-nV1fUNEyMGLQ9NauwZDxBc_bjGZ2Py6N27hHHpDWI9iMo4rsKJqELdHkU-9zBbsZP_EBIxMZv3TSOucACocTOQFxlFw9_XINGINv7OnqX9-Wv1cg&asub=mob&astse=2b844b394383219f&assa=3689',
          attributes: [
            'CI/CD',
            'Permanent',
            'Node.js',
            'React',
            'Full-time',
            'NoSQL',
            'Microservices',
            'SQL',
            'PHP',
            'AWS',
            'Analysis skills',
            'Docker',
            'JavaScript',
            'Distributed systems',
            'Angular',
            'Vue.js',
            'Solution architecture',
            'AI',
            'TypeScript',
            'Communication skills',
            'Python',
            'Debugging',
          ],
        },
      ],
    }.data;

    this.currentJob = this.jobSearchResult[2];
  }
}
